### ISSUE TITLE
Cannot instantiate client

### ISSUE THREAD

**Issue by AustinSeto** [OpenLiberty/guide-graphql-client#1]
Working on the `draft` branch and trying to run the client application does not work. The client cannot be instantiated. Normally you'll get an `InvocationTargetException`. I dug deeper, I moved the following:

```
private GraphQLClient gc = TypesafeGraphQLClientBuilder.newBuilder()
                                                       .build(GraphQLClient.class);
```

I moved this into the methods where it was used so I could get a more detailed view of the error. The following was the output from `docker logs`:

```
[WARNING ] Application {http://client.guides.openliberty.io/}ClientResource has thrown exception, unwinding now
no io.smallrye.graphql.client.typesafe.api.TypesafeGraphQLClientBuilder in classpath
[WARNING ] Exception in handleFault on interceptor org.apache.cxf.jaxrs.interceptor.JAXRSDefaultFaultOutInterceptor@7df2de83
no io.smallrye.graphql.client.typesafe.api.TypesafeGraphQLClientBuilder in classpath
[ERROR   ] An unexpected error occurred during error handling. No further error processing will occur.
no io.smallrye.graphql.client.typesafe.api.TypesafeGraphQLClientBuilder in classpath
[ERROR   ] SRVE0777E: Exception thrown by application class 'org.apache.cxf.service.invoker.AbstractInvoker.createFault:167'
org.apache.cxf.interceptor.Fault: no io.smallrye.graphql.client.typesafe.api.TypesafeGraphQLClientBuilder in classpath
	at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:167)
	at [internal classes]
Caused by: java.util.ServiceConfigurationError: no io.smallrye.graphql.client.typesafe.api.TypesafeGraphQLClientBuilder in classpath
	at io.smallrye.graphql.client.typesafe.api.TypesafeGraphQLClientBuilder.newBuilder(TypesafeGraphQLClientBuilder.java:17)
	at io.openliberty.guides.client.ClientResource.querySystem(ClientResource.java:42)
	at io.openliberty.guides.client.ClientResource$Proxy$_$$_WeldClientProxy.querySystem(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.ibm.ws.jaxrs20.cdi.component.JaxRsFactoryImplicitBeanCDICustomizer.serviceInvoke(JaxRsFactoryImplicitBeanCDICustomizer.java:342)
	... 1 more

[ERROR   ] SRVE0315E: An exception occurred: java.lang.Throwable: org.apache.cxf.interceptor.Fault: no io.smallrye.graphql.client.typesafe.api.TypesafeGraphQLClientBuilder in classpath
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5107)
	at [internal classes]
Caused by: org.apache.cxf.interceptor.Fault: no io.smallrye.graphql.client.typesafe.api.TypesafeGraphQLClientBuilder in classpath
	at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:167)
	... 1 more
Caused by: java.util.ServiceConfigurationError: no io.smallrye.graphql.client.typesafe.api.TypesafeGraphQLClientBuilder in classpath
	at io.smallrye.graphql.client.typesafe.api.TypesafeGraphQLClientBuilder.newBuilder(TypesafeGraphQLClientBuilder.java:17)
	at io.openliberty.guides.client.ClientResource.querySystem(ClientResource.java:42)
	at io.openliberty.guides.client.ClientResource$Proxy$_$$_WeldClientProxy.querySystem(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.ibm.ws.jaxrs20.cdi.component.JaxRsFactoryImplicitBeanCDICustomizer.serviceInvoke(JaxRsFactoryImplicitBeanCDICustomizer.java:342)
	... 1 more
```

For some reason, there is some issue with creating the GraphQL client. I am not sure if this is user error on my part or something else. It is preventing the client app from being used in any way.

**Comment by priyyanshi** [comment]
Bug is not reproducible.

**Comment by priyyanshi** [comment]
Encountered this bug when attempting to make requests using the client.

**Comment by priyyanshi** [comment]
Was resolved by using a version compatible with OL.
